In [20]:
from pandas import Series, DataFrame
import pandas as pd

In [21]:
from __future__ import division
from numpy.random import randn
import numpy as np
import os
import matplotlib.pyplot as plt
np.random.seed(12345)
plt.rc('figure', figsize=(10, 6))
from pandas import Series, DataFrame
import pandas as pd
np.set_printoptions(precision=4)

In [22]:
x = np.array([2, 3, 5, 6, 7, 10])

In [23]:
x

array([ 2,  3,  5,  6,  7, 10])

In [24]:
x**2

array([  4,   9,  25,  36,  49, 100], dtype=int32)

In [25]:
(x**2).sum()

223

In [26]:
x-2

array([0, 1, 3, 4, 5, 8])

In [27]:
(x>5)

array([False, False, False,  True,  True,  True])

In [40]:
x_up = []
for i in x:
    if i>5:
        x_up.append(i)

In [41]:
x_up

[6, 7, 10]

In [42]:
x.size

6

In [44]:
np.dot(x.T,x)

223

In [45]:
np.dot(x,x.T)

223

In [49]:
xc = np.vstack((x, x*2))

In [51]:
xc

array([[ 2,  3,  5,  6,  7, 10],
       [ 4,  6, 10, 12, 14, 20]])

In [52]:
xr = np.hstack((x, x*2))

In [53]:
xr

array([ 2,  3,  5,  6,  7, 10,  4,  6, 10, 12, 14, 20])

In [58]:
np.random.randn(100)

array([-0.6223, -0.9212, -0.7262,  0.2229,  0.0513, -1.1577,  0.8167,
        0.4336,  1.0107,  1.8249, -0.9975,  0.8506, -0.1316,  0.9124,
        0.1882,  2.1695, -0.1149,  2.0037,  0.0296,  0.7953,  0.1181,
       -0.7485,  0.585 ,  0.1527, -1.5657, -0.5625, -0.0327, -0.929 ,
       -0.4826, -0.0363,  1.0954,  0.9809, -0.5895,  1.5817, -0.5287,
        0.457 ,  0.93  , -1.5693, -1.0225, -0.4028,  0.2205, -0.1934,
        0.6692, -1.649 , -2.2528, -1.1668,  0.3536,  0.7021, -0.2746,
       -0.1391,  0.1077, -0.6065, -0.4171, -0.017 , -1.2241, -1.8008,
        1.6347,  0.989 ,  0.4579,  0.5552,  1.3067, -0.4406, -0.3014,
        0.4988, -0.824 ,  1.3206,  0.508 , -0.6534,  0.187 , -0.3917,
       -0.2723, -0.0171,  0.6803,  0.6355, -0.7572,  0.7181, -0.3043,
       -1.6778,  0.427 , -1.5637, -0.3675,  1.0459,  1.22  , -0.2477,
       -0.4162, -0.1167, -1.8448,  2.0687, -0.777 ,  1.4402, -0.1106,
        1.2274,  1.9208,  0.7464,  2.2247, -0.6794,  0.7274, -0.8687,
       -1.2139, -0.4

In [59]:
arr = []
for i in np.random.randn(100):
    if i>0.2:
        arr.append(i)    

In [60]:
arr

[0.43515530456279905,
 1.755108385805539,
 1.2098099860822769,
 1.2700247317379743,
 0.8387750726740476,
 0.26689321273107297,
 0.7211943388971639,
 0.9109826418929284,
 1.2966078419968168,
 0.25227520888346866,
 1.1274811035573475,
 0.3093621681249876,
 1.4572997046385343,
 0.60951184463511,
 1.2399798822830415,
 1.4300418059583067,
 0.6032821300463038,
 1.263572256476092,
 0.46836668123557684,
 0.6254281564975374,
 1.0228723843015668,
 1.107424600768826,
 0.21795701647955643,
 1.43660278579553,
 0.23737226155824268,
 0.940489321395707,
 1.0401792458949988,
 0.4292135883346022,
 0.6418178162604906,
 1.3940722261850058,
 0.42085199690550024,
 0.46457479349887276,
 0.8042226978387959,
 2.0103900112001822,
 0.4833378218776818,
 0.44988041515383903,
 0.399593953414207]

In [65]:
a = np.array([[3, 12, -25], [6, -3, -1], [-5, 2, 4]])
b = np.array([10, 10, 10])


In [73]:
np.linalg.inv(a)

array([[0.0546, 0.5355, 0.4754],
       [0.1038, 0.6175, 0.8033],
       [0.0164, 0.3607, 0.4426]])

In [72]:
numarr = np.linalg.solve(a, b)
numarr

array([10.6557, 15.2459,  8.1967])